import type { Article } from "./types";

export const churchLeadershipTraining: Article = {
  slug: "church-leadership-training",
  title: "Church Leadership Training: Why Most of It Changes Nothing",
  metaTitle: "Church Leadership Training That Actually Forms Leaders",
  metaDescription:
    "After twenty years pastoring in ten countries, here is why most church leadership training fails to change anything, and what forms leaders instead.",
  summary:
    "Most leadership training produces inspired people, not formed ones. Here is what I have seen actually work, and what it costs.",
  date: "August 2026",
  isoDate: "2026-08-23",
  body: [
    { p: "I have sat through leadership training on four continents. Some of it was excellent. Most of it changed nothing, and I include sessions I ran myself in that." },
    { p: "The pattern is easy to miss because the training itself usually goes well. People take notes. Someone cries during the closing prayer. Everyone leaves encouraged. Then six weeks later the same deacon is still avoiding the same conversation he was avoiding before, and the same young worship leader is still burning out in silence." },
    { p: "Encouragement is not formation. That is the whole problem in one sentence." },
    { h2: "Why information does not close the gap" },
    { p: "Most training treats leadership as information a person lacks. So we give them the information and assume the gap closes. But the deacon avoiding that conversation does not lack information. He knows he should have it. He is afraid. And no amount of teaching on conflict resolution touches fear." },
    { p: "What forms leaders is being watched while they do the hard thing, and then talked to honestly afterwards." },
    { h2: "How Jesus trained the twelve" },
    { p: "This is not a modern management insight. In Mark 9, the disciples are left at the foot of the mountain and cannot drive a spirit out of a boy. They fail publicly, in front of a crowd and a desperate father. Jesus does not remove them from ministry and he does not pretend it went well. He deals with the boy, and then, in the house afterwards, when they ask him privately why they could not do it, he tells them plainly what was missing." },
    { p: "The failure was not an interruption to their training. It was the training." },
    { h2: "Three things that actually form a leader" },
    { p: "In one church I pastored, we stopped running the annual leadership weekend entirely. Instead, every person with responsibility met with someone more experienced once a fortnight for a year. Not a class. A conversation about what they had actually done since the last one. It was slower, cheaper, and far more uncomfortable. It also produced the only leaders from that season who are still standing today." },
    { h3: "Real decisions, not case studies" },
    { p: "A leader grows by carrying something that is genuinely theirs, where the outcome matters and the failure would be public. Give someone a rota to run and let them get it wrong." },
    { h3: "Honest feedback close to the event" },
    { p: "Not an annual review. Within days, while it still stings enough to teach. Most churches are so anxious about discouraging volunteers that we say nothing, and then wonder why nobody grows." },
    { h3: "A relationship that outlasts the programme" },
    { p: "The reason most training evaporates is that the trainer leaves. In 2 Timothy 2:2 Paul tells Timothy to entrust what he has heard to faithful men who will be able to teach others. The word translated entrust is paratithemi, meaning to deposit something valuable with a person for safekeeping, the way you would leave money with someone you trusted. It is not a transfer of information. It is a handing over between two people who know each other." },
    { h2: "Why churches keep choosing conferences anyway" },
    { p: "None of this scales neatly, which is why conferences remain popular. A weekend with a good speaker is easier to organise than two years of awkward fortnightly conversations. But the conference produces inspired people, and inspiration has a half-life of about a fortnight." },
    { h2: "The question worth sitting with" },
    { p: "If you lead a church and you are wondering why your people are not growing despite everything you have put on for them, it is usually not laziness on their part, and usually not a failure of teaching on yours. It is that nobody is close enough to them to tell the truth." },
    { p: "And if you are the leader nobody is close enough to, the one who runs the training, prays for everyone, and has not had an honest conversation about your own life in three years, that is worth naming too. It is the most common thing I see in ministry, and it is the loneliest." },
  ],
};

export const christianMarriageHelp: Article = {
  slug: "christian-marriage-help-real-problem",
  title: "Christian Marriage Help: The Problem You Name Is Rarely the Real One",
  metaTitle: "Christian Marriage Help: Finding the Real Problem",
  metaDescription:
    "After counselling more than a thousand couples, here is why the problem couples name is rarely the one that is actually hurting the marriage.",
  summary:
    "Couples arrive naming money, or sex, or the in-laws. After a thousand of these conversations, I have learned to listen for something underneath.",
  date: "August 2026",
  isoDate: "2026-08-24",
  body: [
    { p: "In more than twenty years of pastoral work I have sat with well over a thousand couples. Almost every one of them arrived able to tell me exactly what was wrong with their marriage. Almost none of them were right." },
    { p: "That is not a criticism. It is simply what happens when you live inside a problem. You describe what you can see, and what you can see is the argument you had on Tuesday, not the thing that made Tuesday possible." },
    { h2: "One question that changes the conversation" },
    { p: "There is a question I ask early, and it does more work than anything else I know: if this problem disappeared tomorrow, would your marriage be healthy?" },
    { p: "A couple tells me they fight about the children. So I ask: if the children behaved perfectly from tomorrow morning, would the two of you be well? There is usually a pause. Then, quietly, one of them says no. That pause is where the real conversation begins." },
    { h2: "What money arguments are usually about" },
    { p: "Money is the most common thing couples name, and it is almost never about arithmetic. When a wife says you spend too much, she often means I do not feel secure with you. When a husband says she never lets me buy anything, he often means I feel controlled in my own home." },
    { p: "You can build them a budget. They will keep having the same fight, because the budget was never the disagreement. Trust was." },
    { h2: "What a struggling sex life is usually telling you" },
    { p: "Couples come to me describing mismatched desire. Sometimes that is genuinely the issue. More often the bedroom is simply the room where everything else becomes visible: the resentment nobody named, the apology that never came, the slow loss of affection over years." },
    { p: "Trying to repair physical intimacy while the emotional relationship is dead is like fixing a tap in a house with no water supply." },
    { h2: "When the dishes are not about the dishes" },
    { p: "He never helps around the house is rarely a scheduling complaint. Underneath it is usually this: I feel like you take everything I do for granted. The dishes are just where that feeling finally became sayable." },
    { h2: "The spiritual answer that becomes a hiding place" },
    { p: "This next part is difficult to write as a pastor, and I want to be careful with it." },
    { p: "Sometimes a couple tells me they simply need to pray more. Sometimes they tell me the enemy is attacking their marriage. I believe in prayer, and I believe the enemy is real and does not love what God has joined. I have prayed with couples and seen God do what no counselling could." },
    { p: "But I have also sat with a husband who told me for forty minutes that the devil was attacking his home, when what his wife needed to hear was four words: I was wrong, forgive me. Spiritual language can become the most respectable way to avoid saying them." },
    { p: "Prayer is not a substitute for repentance. It is not a substitute for a boundary you have refused to set, an apology you have not made, or a habit you have not changed. When a couple is spiritually active and relationally immature, more prayer meetings will not close that gap. Only honesty will." },
    { h2: "The five layers underneath a complaint" },
    { p: "When someone brings me a complaint, I listen for five things underneath it. Take he never helps around the house." },
    { list: [
      "The complaint: he never helps around the house.",
      "The feeling: I am overwhelmed and unappreciated.",
      "The belief: he does not value what I do.",
      "The fear: I am alone in this marriage.",
      "The need: partnership, appreciation, and security.",
    ] },
    { p: "Nobody arrives saying I am afraid I am alone in this marriage. They arrive talking about dishes. The work is getting from the first line to the last one, and most couples cannot do it by themselves, because the moment one of them starts down that path the other hears an accusation and defends." },
    { h2: "The question that moves a marriage" },
    { p: "There is one more shift, and for Christian couples it is the important one. Most couples come wanting an answer to who is wrong. That question has never healed a marriage in my experience, because both of them are partly right, and being right has never once made anybody feel loved." },
    { p: "The better question is this: what is my responsibility before God in this marriage? Not his. Not hers. Mine." },
    { p: "It is a harder question, and it is the only one either person can actually act on tomorrow morning." },
  ],
};

export const christianDatingAdvice: Article = {
  slug: "christian-dating-advice-wrong-question",
  title: "Christian Dating Advice: You Are Asking the Wrong Question",
  metaTitle: "Christian Dating Advice From a Pastor of Twenty Years",
  metaDescription:
    "Most Christian dating advice teaches you to discern God's will. After twenty years preparing couples for marriage, here is the question that matters more.",
  summary:
    "Christian singles are taught to ask how do I know God's will. The more useful question is how do I become someone capable of a healthy marriage.",
  date: "August 2026",
  isoDate: "2026-08-24",
  body: [
    { p: "I have prepared a great many couples for marriage, and I have also sat with people years later when those marriages were in trouble. That second conversation teaches you things about the first one." },
    { p: "What I have come to believe is that most Christian singles are not struggling because they cannot find a Christian spouse. They are struggling because they have been handed a model of dating that asks how do I know God's will far more often than it asks how do I become a person capable of choosing well and staying." },
    { h2: "The question almost nobody asks" },
    { p: "Christian singles will spend months asking whether someone loves God. It is the right question, and it is nowhere near enough." },
    { p: "I have watched people conduct what amounts to a spiritual background check and never once ask the question that would have told them most: how does he treat people when he is angry? What does she do when she is embarrassed in front of others? How does he speak to a waiter who has got the order wrong?" },
    { p: "A person can love God sincerely and still be controlling, dishonest, emotionally absent, or unable to apologise. Biblical knowledge and relational competence are different things, and the second one is what you will live with." },
    { h2: "When someone says God told them you are their spouse" },
    { p: "I want to be direct about this one, because I have seen the damage it does." },
    { p: "If a person tells you that God has revealed to them that you are their husband or wife, you are under no obligation whatsoever to agree. None. Their sense of revelation does not bind your conscience, override your discernment, or remove your right to say no." },
    { p: "God is perfectly capable of telling you as well. If he has not, that is information." },
    { p: "I say this carefully, because I do believe God guides people. But I have watched this sentence used as pressure, most often by a man on a younger woman, in a way that makes refusal feel like disobedience to God rather than a decision about a person. That is not prophecy. It is manipulation borrowing God's authority, and you are allowed to name it." },
    { h2: "Marriage is not a treatment for anything" },
    { p: "Some Christian singles are so focused on avoiding sexual sin that marriage becomes the remedy. Get married quickly, and the struggle ends." },
    { p: "It does not work like that. Marriage is not a treatment for lust, loneliness, insecurity, or emotional dependency. Whatever you have not dealt with while single, you carry through the door with you, and now there is another person living inside it with you." },
    { p: "I have sat with couples eighteen months in who married fast for exactly this reason, and the presenting struggle had not gone anywhere. It had simply acquired a witness." },
    { h2: "Three smaller things worth correcting" },
    { h3: "Signs are not the same as discernment" },
    { p: "Seeing her name three times in a day is a coincidence. Feeling something when he walks into church is attraction. A sermon about marriage on the Sunday you were thinking about marriage is a sermon. God can speak through any of these, but character observed over time will tell you more than any of them, and it will not mislead you." },
    { h3: "Conflict is not a verdict" },
    { p: "Some singles expect a Christian relationship to be unusually peaceful, so the first serious disagreement feels like a sign to leave. Healthy relationships do not avoid conflict. They teach two people how to handle it. The question is never do we disagree. It is what happens when we do." },
    { h3: "You do not have to be fully healed first" },
    { p: "Working on yourself is right. Waiting until you are a finished person is another way of never starting. The standard is not that you have no wounds. It is that you are self-aware, taking responsibility, willing to grow, and able to treat another person well." },
    { h2: "The better question" },
    { p: "Instead of asking who is my soulmate, ask who is a wise, healthy, compatible person with whom I could build a marriage that lasts. Christian marriage is not the discovery of one magical human being God assigned to you. It is two people making a covenant and then keeping it, over decades, on ordinary days." },
    { p: "And instead of asking how do I know God's will for my dating life, ask what kind of person I am becoming while I wait. That is the question you can actually answer this year, and it is the one that will still matter twenty years into a marriage." },
  ],
};

export const ALL_ARTICLES: Article[] = [christianDatingAdvice, christianMarriageHelp, churchLeadershipTraining];
