import type { CSSProperties, ReactElement } from "react";

/**
 * The line illustrations for Lead Before You're Ready.
 *
 * Generated by scripts/extract-lbyr-slides.mjs from the ART maps in the pilot
 * pages — do not edit by hand; re-run the extractor. They are JSX rather than
 * SVG strings so nothing in this course sets raw markup, which is how Talk
 * Before You Marry carries its own.
 *
 * Most illustrations are the same in every pilot and live in BASE. A few are
 * not: lesson 2 draws some of them differently, and because those names are
 * used by other lessons too, one merged map would have shown the wrong picture
 * on one side or the other. Those live in BY_LESSON and win for that lesson.
 *
 * artFor() is what a page should call. An unknown name renders nothing, which
 * is what a missing illustration should do.
 */
const BASE: Record<string, ReactElement> = {
  arrow: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><circle className="draw" pathLength="1" cx="100" cy="80" r="52"/><path className="draw s2" style={{ "--d": ".8s" } as CSSProperties} pathLength="1" d="M72 80L128 80M110 62L128 80L110 98"/></svg>
  ),
  book: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M100 40C80 30 50 30 30 38L30 120C50 112 80 112 100 122Z"/><path className="draw" style={{ "--d": ".4s" } as CSSProperties} pathLength="1" d="M100 40C120 30 150 30 170 38L170 120C150 112 120 112 100 122Z"/><path className="draw s2" style={{ "--d": "1s" } as CSSProperties} pathLength="1" d="M45 58C62 54 78 56 90 62M45 76C62 72 78 74 90 80M110 62C122 56 138 54 155 58M110 80C122 74 138 72 155 76"/></svg>
  ),
  bush: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M100 144L100 106M100 118L78 100M100 110L124 92"/><g className="flick"><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M100 104C66 84 70 46 88 30C90 52 102 56 100 72C112 60 120 46 116 30C138 46 140 84 100 104Z"/></g><path className="draw" style={{ "--d": "1.3s" } as CSSProperties} pathLength="1" d="M76 144L124 144"/><circle className="pop f" style={{ "--d": "1.8s" } as CSSProperties} cx="100" cy="78" r="4"/></svg>
  ),
  candle: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M82 84L82 142L118 142L118 84Z"/><path className="draw s2" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M100 84L100 72"/><g className="flick"><path className="draw" style={{ "--d": ".9s" } as CSSProperties} pathLength="1" d="M100 70C84 54 94 38 100 24C106 38 116 54 100 70Z"/></g><path className="draw s2 faded" style={{ "--d": "1.6s" } as CSSProperties} pathLength="1" d="M58 58L70 64M142 58L130 64M52 84L66 84M148 84L134 84"/></svg>
  ),
  chain: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><rect className="draw" pathLength="1" x="30" y="60" width="50" height="34" rx="17"/><rect className="draw s2" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" x="70" y="60" width="50" height="34" rx="17"/><rect className="draw" style={{ "--d": "1s" } as CSSProperties} pathLength="1" x="110" y="60" width="50" height="34" rx="17"/><path className="draw faded" style={{ "--d": "1.6s" } as CSSProperties} pathLength="1" d="M100 40L100 20M92 28L100 20L108 28"/></svg>
  ),
  clock: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><circle className="draw" pathLength="1" cx="100" cy="82" r="52"/><path className="draw s2" style={{ "--d": ".9s" } as CSSProperties} pathLength="1" d="M100 82L100 46M100 82L126 96"/><circle className="pop f" style={{ "--d": "1.6s" } as CSSProperties} cx="100" cy="82" r="4"/></svg>
  ),
  dawn: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M20 110L180 110"/><g className="loop"><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M60 110C60 88 78 74 100 74C122 74 140 88 140 110"/></g><path className="draw faded" style={{ "--d": "1.2s" } as CSSProperties} pathLength="1" d="M100 52L100 40M64 64L56 56M136 64L144 56M44 100L32 100M156 100L168 100"/></svg>
  ),
  door: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M20 140L60 140L60 116L92 116L92 92L124 92L124 68"/><path className="draw" style={{ "--d": ".6s" } as CSSProperties} pathLength="1" d="M124 68L124 22L168 22L168 140L124 140"/><path className="draw" style={{ "--d": "1.2s" } as CSSProperties} pathLength="1" d="M168 22L184 34L184 148L168 140"/><circle className="pop f" style={{ "--d": "1.9s" } as CSSProperties} cx="176" cy="86" r="3.5"/></svg>
  ),
  fishermen: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M30 104C50 96 150 96 170 104L156 128L44 128Z"/><path className="draw s2" style={{ "--d": ".7s" } as CSSProperties} pathLength="1" d="M100 100L100 40L140 62L100 72"/><path className="draw s2 faded" style={{ "--d": "1.4s" } as CSSProperties} pathLength="1" d="M20 140C40 132 60 148 80 140C100 132 120 148 140 140C160 132 180 148 190 140"/><circle className="pop f" style={{ "--d": "1.9s" } as CSSProperties} cx="62" cy="86" r="5"/><circle className="pop f" style={{ "--d": "2.1s" } as CSSProperties} cx="84" cy="86" r="5"/></svg>
  ),
  four: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><rect className="draw" pathLength="1" x="34" y="30" width="56" height="44" rx="6"/><rect className="draw s2" style={{ "--d": ".4s" } as CSSProperties} pathLength="1" x="110" y="30" width="56" height="44" rx="6"/><rect className="draw s2" style={{ "--d": ".8s" } as CSSProperties} pathLength="1" x="34" y="88" width="56" height="44" rx="6"/><rect className="draw" style={{ "--d": "1.2s" } as CSSProperties} pathLength="1" x="110" y="88" width="56" height="44" rx="6"/><circle className="pop f" style={{ "--d": "1.6s" } as CSSProperties} cx="62" cy="52" r="4"/><circle className="pop f" style={{ "--d": "1.8s" } as CSSProperties} cx="138" cy="52" r="4"/><circle className="pop f" style={{ "--d": "2s" } as CSSProperties} cx="62" cy="110" r="4"/><circle className="pop f" style={{ "--d": "2.2s" } as CSSProperties} cx="138" cy="110" r="4"/></svg>
  ),
  helmet: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M50 100C50 60 150 60 150 100L150 116L50 116Z"/><path className="draw s2" style={{ "--d": ".6s" } as CSSProperties} pathLength="1" d="M100 40L100 100"/><path className="draw s2" style={{ "--d": "1s" } as CSSProperties} pathLength="1" d="M70 40C90 30 110 30 130 40"/><path className="draw faded" style={{ "--d": "1.5s" } as CSSProperties} pathLength="1" d="M60 128L140 128"/></svg>
  ),
  letter: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M30 40L170 40L170 124L30 124Z"/><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M30 40L100 92L170 40"/><path className="draw s2 faded" style={{ "--d": "1.2s" } as CSSProperties} pathLength="1" d="M60 136L140 136"/><g className="loop"><circle className="draw s2" style={{ "--d": "1.4s" } as CSSProperties} pathLength="1" cx="100" cy="82" r="10"/></g></svg>
  ),
  pause: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><g className="loop"><circle className="draw" pathLength="1" cx="100" cy="80" r="54"/></g><path className="draw s2" style={{ "--d": ".8s" } as CSSProperties} pathLength="1" d="M84 58L84 102M116 58L116 102"/></svg>
  ),
  pencil: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M34 122L42 96L122 16L148 42L68 122ZM42 96L68 122L34 122Z"/><path className="draw s2" style={{ "--d": "1s" } as CSSProperties} pathLength="1" d="M92 138L172 138M112 118L172 118M132 98L172 98"/></svg>
  ),
  presence: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M56 140L56 100L44 100L60 70L76 100L64 100L64 140Z"/><g className="loop"><circle className="draw" style={{ "--d": ".6s" } as CSSProperties} pathLength="1" cx="126" cy="70" r="40"/></g><path className="draw faded" style={{ "--d": "1.4s" } as CSSProperties} pathLength="1" d="M126 18L126 8M178 70L188 70M163 33L170 26M163 107L170 114"/><circle className="pop f" style={{ "--d": "1.9s" } as CSSProperties} cx="126" cy="70" r="6"/></svg>
  ),
  scales: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M100 28L100 136M72 136L128 136"/><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M40 52L160 52"/><path className="draw" style={{ "--d": "1s" } as CSSProperties} pathLength="1" d="M40 52L26 92L54 92ZM160 52L146 92L174 92Z"/><circle className="pop f" style={{ "--d": "1.7s" } as CSSProperties} cx="100" cy="28" r="5"/></svg>
  ),
  scales2: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M100 28L100 136M72 136L128 136"/><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M40 52L160 52"/><path className="draw" style={{ "--d": "1s" } as CSSProperties} pathLength="1" d="M40 52L26 92L54 92ZM160 52L146 92L174 92Z"/></svg>
  ),
  speak: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M30 40L130 40L130 100L70 100L52 118L56 100L30 100Z"/><path className="draw s2" style={{ "--d": ".8s" } as CSSProperties} pathLength="1" d="M50 60L110 60M50 80L96 80"/><path className="draw faded" style={{ "--d": "1.4s" } as CSSProperties} pathLength="1" d="M146 60L172 60M146 80L172 80"/></svg>
  ),
  star: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><g className="loop"><path className="draw" pathLength="1" d="M100 22L114 62L156 62L122 86L134 128L100 102L66 128L78 86L44 62L86 62Z"/></g><circle className="pop f" style={{ "--d": "1.6s" } as CSSProperties} cx="100" cy="82" r="5"/></svg>
  ),
  tables: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M30 70L170 70L170 80L30 80Z"/><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M44 80L44 130M156 80L156 130"/><circle className="pop f" style={{ "--d": "1s" } as CSSProperties} cx="70" cy="50" r="7"/><circle className="pop f" style={{ "--d": "1.2s" } as CSSProperties} cx="100" cy="50" r="7"/><circle className="pop f" style={{ "--d": "1.4s" } as CSSProperties} cx="130" cy="50" r="7"/></svg>
  ),
  thought: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><circle className="draw s2" pathLength="1" cx="58" cy="118" r="22"/><circle className="pop" style={{ "--d": ".9s;fill:var(--cream);stroke:none" } as CSSProperties} cx="86" cy="86" r="5"/><circle className="pop" style={{ "--d": "1.1s;fill:var(--cream);stroke:none" } as CSSProperties} cx="98" cy="70" r="4"/><ellipse className="draw" style={{ "--d": "1.2s" } as CSSProperties} pathLength="1" cx="132" cy="50" rx="46" ry="30"/><path className="draw s2" style={{ "--d": "2s" } as CSSProperties} pathLength="1" d="M124 40C124 32 140 32 140 40C140 47 132 47 132 54"/><circle className="pop f" style={{ "--d": "2.6s" } as CSSProperties} cx="132" cy="62" r="3"/></svg>
  ),
  three: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><circle className="pop f" style={{ "--d": ".2s" } as CSSProperties} cx="40" cy="44" r="7"/><path className="draw s2" style={{ "--d": ".4s" } as CSSProperties} pathLength="1" d="M62 44L160 44"/><circle className="pop f" style={{ "--d": ".8s" } as CSSProperties} cx="40" cy="80" r="7"/><path className="draw s2" style={{ "--d": "1s" } as CSSProperties} pathLength="1" d="M62 80L160 80"/><circle className="pop f" style={{ "--d": "1.4s" } as CSSProperties} cx="40" cy="116" r="7"/><path className="draw s2" style={{ "--d": "1.6s" } as CSSProperties} pathLength="1" d="M62 116L160 116"/></svg>
  ),
  two: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><circle className="draw" pathLength="1" cx="66" cy="60" r="18"/><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M36 126C36 96 96 96 96 126"/><circle className="draw s2" style={{ "--d": ".8s" } as CSSProperties} pathLength="1" cx="134" cy="60" r="18"/><path className="draw s2" style={{ "--d": "1.3s" } as CSSProperties} pathLength="1" d="M104 126C104 96 164 96 164 126"/></svg>
  ),
  vineyard: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M30 140L170 140M50 140L50 60M100 140L100 44M150 140L150 60"/><path className="draw" style={{ "--d": ".6s" } as CSSProperties} pathLength="1" d="M50 80C70 70 80 90 100 80C120 70 130 90 150 80"/><path className="draw" style={{ "--d": "1s" } as CSSProperties} pathLength="1" d="M50 110C70 100 80 120 100 110C120 100 130 120 150 110"/><circle className="pop f" style={{ "--d": "1.6s" } as CSSProperties} cx="75" cy="76" r="4"/><circle className="pop f" style={{ "--d": "1.8s" } as CSSProperties} cx="125" cy="76" r="4"/><circle className="pop f" style={{ "--d": "2s" } as CSSProperties} cx="100" cy="106" r="4"/></svg>
  ),
  word: (
    <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M28 110L60 110L60 60L28 60"/><path className="draw" style={{ "--d": ".3s" } as CSSProperties} pathLength="1" d="M172 110L140 110L140 60L172 60"/><path className="draw s2" style={{ "--d": ".9s" } as CSSProperties} pathLength="1" d="M76 84L124 84"/><circle className="pop f" style={{ "--d": "1.6s" } as CSSProperties} cx="100" cy="84" r="6"/><path className="draw s2 faded" style={{ "--d": "1.8s" } as CSSProperties} pathLength="1" d="M100 40L100 62M100 106L100 128"/></svg>
  ),
};

const BY_LESSON: Record<string, Record<string, ReactElement>> = {
  "lesson-02": {
    clock: (
      <svg viewBox="0 0 200 160" aria-hidden="true"><circle className="draw" pathLength="1" cx="100" cy="82" r="52"/><path className="draw s2" style={{ "--d": ".9s" } as CSSProperties} pathLength="1" d="M100 82L100 46M100 82L126 96"/><circle className="pop f" style={{ "--d": "1.6s" } as CSSProperties} cx="100" cy="82" r="4"/><path className="draw faded" style={{ "--d": "1.8s" } as CSSProperties} pathLength="1" d="M100 36L100 30M146 82L152 82M100 128L100 134M54 82L48 82"/></svg>
    ),
    dawn: (
      <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw s2" pathLength="1" d="M20 110L180 110"/><g className="loop"><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M60 110C60 88 78 74 100 74C122 74 140 88 140 110"/></g><path className="draw faded" style={{ "--d": "1.2s" } as CSSProperties} pathLength="1" d="M100 52L100 40M64 64L56 56M136 64L144 56M44 100L32 100M156 100L168 100"/><path className="draw s2" style={{ "--d": "1.8s" } as CSSProperties} pathLength="1" d="M150 140L160 122L170 140"/></svg>
    ),
    tables: (
      <svg viewBox="0 0 200 160" aria-hidden="true"><path className="draw" pathLength="1" d="M30 70L170 70L170 80L30 80Z"/><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M44 80L44 130M156 80L156 130"/><circle className="pop f" style={{ "--d": "1s" } as CSSProperties} cx="70" cy="50" r="7"/><circle className="pop f" style={{ "--d": "1.2s" } as CSSProperties} cx="100" cy="50" r="7"/><circle className="pop f" style={{ "--d": "1.4s" } as CSSProperties} cx="130" cy="50" r="7"/><path className="draw s2" style={{ "--d": "1.8s" } as CSSProperties} pathLength="1" d="M60 110L140 110"/></svg>
    ),
    two: (
      <svg viewBox="0 0 200 160" aria-hidden="true"><circle className="draw" pathLength="1" cx="66" cy="60" r="18"/><path className="draw" style={{ "--d": ".5s" } as CSSProperties} pathLength="1" d="M36 126C36 96 96 96 96 126"/><circle className="draw s2" style={{ "--d": ".8s" } as CSSProperties} pathLength="1" cx="134" cy="60" r="18"/><path className="draw s2" style={{ "--d": "1.3s" } as CSSProperties} pathLength="1" d="M104 126C104 96 164 96 164 126"/><path className="draw" style={{ "--d": "1.9s" } as CSSProperties} pathLength="1" d="M88 70C96 78 104 78 112 70"/></svg>
    ),
  },
};

export function artFor(lesson: number, key: string | undefined): ReactElement | null {
  if (!key) return null;
  const slug = "lesson-" + String(lesson).padStart(2, "0");
  return BY_LESSON[slug]?.[key] ?? BASE[key] ?? null;
}
